Challenges/one and two
nightlaro/kotlin-funda-two pull request #1
Opened 2021-08-06 18:30 UTC by nightlaro

hold on... to your cats

2021-08-06 21:35 UTC, vaudevillen commented on src/main/kotlin/DelegatedProperties.kt
> +    val ingredients: ArrayList<String> by lazy { arrayListOf("Milk", "Sleep", "green flowers that can be made into strong ropes") }
it'd be easier to read if you split this up across multiple lines

2021-08-06 21:39 UTC, vaudevillen commented on src/main/kotlin/DelegatedProperties.kt
> +    val ingredients: ArrayList<String> by lazy { arrayListOf("Milk", "Sleep", "green flowers that can be made into strong ropes") }
also, interesting with the ropes

2021-08-06 21:41 UTC, vaudevillen commented on src/main/kotlin/DelegatedProperties.kt
> +    fun fly(am: Int) {
let's avoid these abbreviations for small words in functions

2021-08-06 21:43 UTC, vaudevillen commented on src/main/kotlin/DelegatedProperties.kt
> +    var level by Delegates.observable(0.0) { _, old, new ->
whoa...! I've never used `Delegates.observable`, but it looks really dope.

2021-08-06 21:45 UTC, vaudevillen commented on src/main/kotlin/LambdasAndHigherOrder.kt
> +    libraryBooks = listOf("The Book of Atrus", "Living by the Code", "Mastering Git"))
when you're passing more than two or three arguments, let's break it up into multiple lines, i.e.
```
val chris = Student(
   name = "Chris",
   grade = 49, 
   pet = "Mango",
   libraryBooks = listOf("The Book of Atrus", "Living by the Code", "Mastering Git")
)
```

2021-08-06 21:46 UTC, vaudevillen commented on src/main/kotlin/LambdasAndHigherOrder.kt
> +    libraryBooks = listOf("The Book of Atrus", "Living by the Code", "Mastering Git"))
Also, i'm aware you probably copied and pasted this. just something to consider in the future.

2021-08-06 21:48 UTC, vaudevillen commented on src/main/kotlin/MethodsAndExtension.kt
> +            field = sqrt(value / PI)
Is the radius getting updated when you change the area?

2021-08-06 21:49 UTC, vaudevillen commented on src/main/kotlin/MethodsAndExtension.kt
> +object MyMath {
quick question: what's an `object`? How is it different from a `class`?

2021-08-06 21:54 UTC, vaudevillen requested changes
Oooh, so close. You just need to fix up how you're updating the `radius` and `area` in your `Circle` class, otherwise everything looks great

2021-08-09 21:58 UTC, nightlaro commented on src/main/kotlin/DelegatedProperties.kt
> +    var level by Delegates.observable(0.0) { _, old, new ->
it was a holy shit moment for me!

2021-08-09 22:01 UTC, nightlaro commented on src/main/kotlin/MethodsAndExtension.kt
> +            field = sqrt(value / PI)
Ah yes thank you

2021-08-09 22:08 UTC, nightlaro commented on src/main/kotlin/MethodsAndExtension.kt
> +object MyMath {
an `object` can only have one instance and does not have a constructor, while `classes` can have constructors

`object` is particularly useful for this fancy word being thrown around ... `singleton` pattern

`object` also introduces a global state and sometimes is frowned upon

So I feel like `object` is like a `class`, it can have methods, properties, and inherit a class, but has limitations/restrictions like
- can only have one instance
- properties must be initialized (on declaration or inside of a init() block)

downside -> introduces a global state

2021-08-09 22:16 UTC, asarazan commented on src/main/kotlin/CustomAccessorAndCompanionObjects.kt
> +        get() = "$firstName $lastName"
@vaudevillen may disagree on this, but as a stylistic point I generally try to put the getter first, as it's generally simpler and makes the code flow a little nicer.

2021-08-10 00:27 UTC, vaudevillen commented on src/main/kotlin/MethodsAndExtension.kt
> +object MyMath {
😭 
so proud!
Also with `singleton`, the key there is `single`: there can be only one of them.

2021-08-10 00:28 UTC, vaudevillen approved these changes

2021-08-10 00:31 UTC, merged